DROP DATABASE IF EXISTS electronicsst;
CREATE DATABASE electronicsst;
USE electronicsst;

CREATE TABLE IF NOT EXISTS usuario(
	idusuario INT(11) NOT NULL AUTO_INCREMENT,
	nomeusuario VARCHAR(30) NOT NULL,
	sobrenomeusuario VARCHAR(30) NOT NULL,
	email VARCHAR(60) NOT NULL,
	senha VARCHAR(30) NOT NULL,
	cpf VARCHAR(14) NOT NULL,
	datadenascimento VARCHAR(10) NOT NULL,
	sexo VARCHAR(10) NOT NULL,
	tipousuario VARCHAR(15) NOT NULL,
	PRIMARY KEY(idusuario)
);
CREATE TABLE IF NOT EXISTS categoria(
	idcategoria INT NOT NULL AUTO_INCREMENT,
	descricao VARCHAR(50) NOT NULL,
	PRIMARY KEY(idcategoria)
);
CREATE TABLE IF NOT EXISTS produto(
	idproduto INT(11) NOT NULL AUTO_INCREMENT,
	idcategoria INT NOT NULL,
	preco DOUBLE NOT NULL,
	nomeproduto VARCHAR(30) NOT NULL,
	descricao VARCHAR(60) NOT NULL,
	imagem VARCHAR(60) NOT NULL,
	estoque_minimo INT(11) NOT NULL,
	estoque_maximo INT(11) NOT NULL,
	PRIMARY KEY(idproduto),
	FOREIGN KEY(idcategoria) REFERENCES categoria(idcategoria) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS endereco(
	idEndereco INT(11) NOT NULL AUTO_INCREMENT,
	idUsuario INT (11) NOT NULL,
	logradouro VARCHAR(20) NOT NULL,
	complemento VARCHAR(20),
	bairro VARCHAR(30) NOT NULL,
	cidade VARCHAR(30) NOT NULL,
	cep VARCHAR(8) NOT NULL,
	PRIMARY KEY(idEndereco, idUsuario),
	FOREIGN KEY(idUsuario) REFERENCES usuario(idUsuario) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS cupom(
	idCupom INT(8) NOT NULL AUTO_INCREMENT,
	nomecupom VARCHAR(20) NOT NULL,
	desconto INT(8) NOT NULL,
	PRIMARY KEY(idCupom)
);
CREATE TABLE IF NOT EXISTS log_produto(
	ID_Log INT(11) NOT NULL AUTO_INCREMENT,
	tabela VARCHAR(45) NOT NULL,
	usuario VARCHAR(45) NOT NULL,
	data_hora DATETIME NOT NULL,
	acao VARCHAR(45) NOT NULL,
	dados VARCHAR(1000) NOT NULL,
	PRIMARY KEY(ID_Log)
);
CREATE TABLE IF NOT EXISTS  pedido (
	idPedido INT(11) NOT NULL AUTO_INCREMENT,
	idUsuario INT(11) NOT NULL,
	idEndereco INT(11) NOT NULL,
	dataCompra DATE NOT NULL,
	PRIMARY KEY(idPedido),
	FOREIGN KEY(idUsuario) REFERENCES usuario(idUsuario) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(idEndereco) REFERENCES endereco(idEndereco) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS pedido_produto(
	idProduto INT(11) NOT NULL,
	idPedido INT(11) NOT NULL,
	quantidade INT(11) NOT NULL,
	PRIMARY KEY(idProduto, idPedido),
	FOREIGN KEY(idProduto) REFERENCES produto(idProduto) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(idPedido) REFERENCES pedido(idPedido) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS estoque(
	idEstoque INT(11) NOT NULL AUTO_INCREMENT,
	idProduto INT(11) NOT NULL,
	quantidade INT(11) NOT NULL,
	PRIMARY KEY(idEstoque),
	FOREIGN KEY(idProduto) REFERENCES produto(idProduto) ON UPDATE CASCADE ON DELETE CASCADE
);

ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8
