DROP DATABASE IF EXISTS electronicsst;
CREATE DATABASE electronicsst;
USE electronicsst;

CREATE TABLE IF NOT EXISTS usuario(
	cpf BIGINT(11) NOT NULL,
	nome VARCHAR(60) NOT NULL,
	email VARCHAR(40) NOT NULL,
	senha VARCHAR(16) NOT NULL,
	nascimento VARCHAR(10) NOT NULL,
	sexo VARCHAR(1) NOT NULL,
	tipoUsuario VARCHAR(5) NOT NULL,
	PRIMARY KEY(cpf)
);

CREATE TABLE IF NOT EXISTS categoria(
	idcategoria BIGINT(11) NOT NULL AUTO_INCREMENT,
	descricao VARCHAR(30) NOT NULL,
	PRIMARY KEY(idCategoria)
);

CREATE TABLE IF NOT EXISTS cupom(
	idcupom INT(8) NOT NULL AUTO_INCREMENT,
	nomecupom VARCHAR(20) NOT NULL,
	desconto INT(4) NOT NULL,
	PRIMARY KEY(idCupom)
);

CREATE TABLE IF NOT EXISTS log_produto(
	ID_Log BIGINT(11) NOT NULL AUTO_INCREMENT,
	tabela VARCHAR(45) NOT NULL,
	usuario VARCHAR(45) NOT NULL,
	data_hora DATETIME NOT NULL,
	acao VARCHAR(45) NOT NULL,
	dados VARCHAR(1000) NOT NULL,
	PRIMARY KEY(ID_Log)
);

CREATE TABLE IF NOT EXISTS produto(
	idproduto BIGINT(11) NOT NULL AUTO_INCREMENT,
	idcategoria BIGINT(11) NOT NULL,
	nomeproduto VARCHAR(30) NOT NULL,
	preco DOUBLE NOT NULL,
	descricao VARCHAR(800) NOT NULL,
	imagem VARCHAR(100) NOT NULL,
	estoque_minimo BIGINT(11) NOT NULL,
	estoque_maximo BIGINT(11) NOT NULL,
	PRIMARY KEY(idproduto),
	FOREIGN KEY(idcategoria) REFERENCES categoria(idcategoria) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS endereco(
	idEndereco INT(11) NOT NULL AUTO_INCREMENT,
	idUsuario INT (11) NOT NULL,
	logradouro VARCHAR(50) NOT NULL,
        numero VARCHAR(7) NOT NULL,
	complemento VARCHAR(20),
	bairro VARCHAR(30) NOT NULL,
	cidade VARCHAR(30) NOT NULL,
	cep VARCHAR(8) NOT NULL,
	PRIMARY KEY(idEndereco),
	FOREIGN KEY(idUsuario) REFERENCES usuario(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS  pedido (
	idPedido BIGINT(11) NOT NULL AUTO_INCREMENT,
	idUsuario BIGINT(11) NOT NULL,
	idEndereco BIGINT(11) NOT NULL,
	dataCompra DATE NOT NULL,
	PRIMARY KEY(idPedido),
	FOREIGN KEY(idUsuario) REFERENCES usuario(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(idEndereco) REFERENCES endereco(idEndereco) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS pedido_produto(
	idPedido BIGINT(11) NOT NULL,
	idProduto BIGINT(11) NOT NULL,
	quantidade INT(5) NOT NULL,
	PRIMARY KEY(idProduto, idPedido),
	FOREIGN KEY(idProduto) REFERENCES produto(idProduto) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(idPedido) REFERENCES pedido(idPedido) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS estoque(
	idEstoque BIGINT(11) NOT NULL AUTO_INCREMENT,
	idProduto BIGINT(11) NOT NULL,
	quantidade INT(8) NOT NULL,
	PRIMARY KEY(idEstoque),
	FOREIGN KEY(idProduto) REFERENCES produto(idProduto) ON DELETE CASCADE ON UPDATE CASCADE
);
